name = "matrix example"
resources = ["fake-device-1", "fake-device-2", "fake-device-3"]

[matrix]
content = ["a", "b", "c"]

[tasks.a]
command = "sleep 1 && echo '{content}:a'"

[tasks.b]
command = "sleep 2 && echo '{content}:b'"

[tasks.c]
command = "sleep {time} && echo '{content}:c'"

[tasks.c.matrix]
time = ["1", "2", "3"]

[tasks.d]
command = "sleep 1 && echo '{content}:d'"
# You can't depend on a task that has matrix, such as c.
deps = ["a", "b"]
