name = "simple example"
resources = ["fake-device-1", "fake-device-2"]

[tasks.a]
command = "sleep 0.1 && echo 'a'"

[tasks.b]
command = "sleep 0.2 && echo 'b'"

[tasks.c]
command = "sleep 0.1 && echo 'c'"
deps = ["a", "b"]
