name: "CI: Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  id-token: write
jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v6
      - name: Setup Just 📦
        uses: extractions/setup-just@v4
      - name: Install the latest version of uv 📦
        uses: astral-sh/setup-uv@v7
      - name: Install python 📦
        uses: actions/setup-python@v6
      - name: Install dependencies 📦
        run: just install
      - name: Run tests and benchmarks ✅
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: just test
      - name: Upload coverage reports to Codecov 📦
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: nanoflow
          plugins: pycoverage,compress-pycoverage
