name: CodeStyle Check

on:
  push:
    branches: [main]
  pull_request:
jobs:
  code-style-check:
    runs-on: ubuntu-latest
    name: CodeStyle Check
    steps:
      - name: Checkout 📦
        uses: actions/checkout@v4
      - name: Install python 📦
        uses: actions/setup-python@v4
      - name: Run pre-commit ✅
        uses: pre-commit/action@v3.0.1
